#!/bin/bash

build_deps=(
    "cmake"
    "doxygen"
    "fakeroot"
    "graphviz"
    "g++"
    "libavahi-client-dev"
    "libavformat58"
    "libavcodec58"
    "libasound2-dev"
    "libbluetooth-dev"
    "libcamera-dev"
	"libcap-dev"
    "libdbus-1-dev"
    "libdrm-dev"
    "libfdk-aac-dev"
    "libglib2.0-dev"
    "libgstreamer-plugins-base1.0-dev"
    "libgstreamer1.0-dev"
    "libjack-jackd2-dev"
    "libldacbt-abr-dev"
    "libldacbt-enc-dev"
    "libncurses-dev"
    "libopenaptx-dev"
    "libpulse-dev"
    "libsbc-dev"
    "libsdl2-dev"
    "libsndfile1-dev"
    "libsystemd-dev"
    "libudev-dev"
    "libv4l-dev"
    "libvulkan-dev"
    "make"
    "meson"
    "valgrind"
    "libwebrtc-audio-processing-dev"
    "xmltoman"
)


echo ${build_deps[@]}
